[Feature/#12] splash screen 구현
TeamDon-tBe/ANDROID pull request #14
Opened 2024-01-04 16:46 UTC by Eonji-sw

## ✅ 𝗖𝗵𝗲𝗰𝗸-𝗟𝗶𝘀𝘁

## 📌 𝗜𝘀𝘀𝘂𝗲𝘀
- closed #12

## 📎𝗪𝗼𝗿𝗸 𝗗𝗲𝘀𝗰𝗿𝗶𝗽𝘁𝗶𝗼𝗻
- 앱 처음 실행시 보이는 splash screen 구현(3s)
- 안드 버전 12 이상/미만 다르게 대응

## 📷 𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁
https://github.com/TeamDon-tBe/ANDROID/assets/85453429/4d92207c-b1da-4fee-9ef7-9308d5446097

## 💬 𝗧𝗼 𝗥𝗲𝘃𝗶𝗲𝘄𝗲𝗿𝘀
- API 30 이상, API 12 이상 30 이하 에뮬로 돌아가는지 체킹 완
- API 12 미만은 체킹 못했어욥
- 얼레벌레 하긴 했는데 스플래쉬 아이콘 사이즈 관련해서 조금 더 수정할 필요도 있을 수 있어욤.. 일단 얼레벌레 맞춘듯?
- 글구 제 공기계가 갤s10인데 여기서는.. 스플래쉬 제대로 작동 안함 ㅠ
- 일단 3초로 해놨는데 아마 추후 수정해야겠죠 ^__^?

2024-01-04 18:13 UTC, chanubc reviewed
제 기기가 s10e인데 스플래시 화면이 나오지 않고 바로 로그인 화면부터 나오네요!

원래대로면 돈비 로고가 나와야 하는거.. 맞죠?

### 짧아서 못 봤습니다 잘 나오네요ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-01-04 18:13 UTC, chanubc commented on feature/src/main/AndroidManifest.xml
> +            android:screenOrientation="portrait"/>
이 부분 conflict날 것 같긴 한데 내일 차근차근 합쳐 봅시다!

2024-01-04 18:13 UTC, chanubc commented on feature/src/main/java/com/teamdontbe/feature/SplashActivity.kt
> +        installSplashScreen()
이렇게 간편할 수가..?
handler 안에 loop를 사용해서 했었던 것 같은데 짱 편하네요!

2024-01-04 18:13 UTC, chanubc commented on feature/src/main/java/com/teamdontbe/feature/SplashActivity.kt
> +        startActivity(Intent(this, LoginActivity::class.java))
한줄 축약 좋아요~

2024-01-04 18:13 UTC, chanubc commented on feature/src/main/res/drawable/img_splash_symbol.xml
path가 긴 svg는 처음 앱이 실행 될때 cpu에 영향을 준다고 들었습니다!
반면 png는 최소 3x는 써야 하는데 이러면 앱 용량이 커져서..
밸런스 게임이네요

다들 어떻게 생각하시나요?

2024-01-04 18:13 UTC, chanubc commented on feature/src/main/res/values-v31/themes.xml
따로 xml을 만들 필요가 없는게 신기하네요!

2024-01-05 09:49 UTC, sohyun127 requested changes
P1 단계 리뷰 수정해서 push 다시 해주세유~~
먼지 최고❤️‍🔥

2024-01-05 09:49 UTC, sohyun127 commented on feature/src/main/AndroidManifest.xml
> +            android:exported="true"
P1 :
```suggestion
            android:exported="false"
```
변경해주십쇼!!

2024-01-05 09:49 UTC, sohyun127 commented on feature/src/main/java/com/teamdontbe/feature/SplashActivity.kt
> +        installSplashScreen()
P1 :
```suggestion
        installSplashScreen()
        super.onCreate(savedInstanceState)
```
순서 바꿔주십쇼!!

2024-01-05 09:49 UTC, sohyun127 commented on feature/src/main/res/drawable/img_splash_symbol.xml
P1 :
path 긴 svg가 cpu에 영향을 주는건 처음 알았네요! 배워갑니다👍
3x 라도 이미지 품질 저하가 일어날 수 있으니
안전하게 갑시다! 저도 svg 추출 가능하면 svg 쓰는 편입니둥-!!

그리고 파일 네이밍 img -> ic 로 변경해주세요!!
(convention 참고)

2024-01-06 05:21 UTC, Eonji-sw commented on feature/src/main/java/com/teamdontbe/feature/SplashActivity.kt
> +        installSplashScreen()
하지만 duration를 조절할 수 없다는 단점이..?

2024-01-06 05:37 UTC, Eonji-sw commented on feature/src/main/res/drawable/img_splash_symbol.xml
저도 svg로 쓰는 편입니당
글구 네이밍 수정 했어요~

2024-01-06 05:51 UTC, Eonji-sw commented on feature/src/main/AndroidManifest.xml
> +            android:exported="true"
앗 했슴다!

2024-01-06 06:02 UTC, Eonji-sw commented on feature/src/main/java/com/teamdontbe/feature/SplashActivity.kt
> +        installSplashScreen()
적용했어요

2024-01-06 06:33 UTC, sohyun127 approved these changes
LGTM 👍  고생하셨습니다-! 컨플릭 해결해주시고 머지해주세요~

2024-01-06 06:40 UTC, merged