[Feature/#17] kakao login 구현
TeamDon-tBe/ANDROID pull request #23
Opened 2024-01-06 08:52 UTC by Eonji-sw

## ✅ 𝗖𝗵𝗲𝗰𝗸-𝗟𝗶𝘀𝘁

## 📌 𝗜𝘀𝘀𝘂𝗲𝘀
- closed #17

## 📎𝗪𝗼𝗿𝗸 𝗗𝗲𝘀𝗰𝗿𝗶𝗽𝘁𝗶𝗼𝗻
- kakao 로그인 구현
- timber로 토큰, 유저 id, 유저 닉네임 확인 가능
- 유저 id, 유저 닉네임의 경우 우선 테스트를 위해 mainActivity에 확인 코드 추가
- 현재 로그인 후 메인 화면으로 넘어가나 추후 회원가입 화면으로 넘어가게 수정 요망

## 📷 𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁

## 💬 𝗧𝗼 𝗥𝗲𝘃𝗶𝗲𝘄𝗲𝗿𝘀
- DI? 때문에 좀 에러가 있었지만 그래도 무사 성공!!
- 이제 맥북으로 가자! (빌드 부들부들..)

2024-01-06 16:31 UTC, chanubc reviewed
저도 다음에 할때 참고할께요ㅎㅎ 빠르게 잘하시네요. 고생하셨습니다!

번호만 똑바로 주셨으면 완벽 했을텐데 아쉽네요^-^

2024-01-06 16:31 UTC, chanubc commented on feature/src/main/java/com/teamdontbe/feature/login/LoginActivity.kt
> +    private fun goMain() {
p2 : goToMainActivity는 어떠신가요?

2024-01-06 16:31 UTC, chanubc commented on feature/src/main/res/layout/activity_login.xml
> +            android:text="온화한 커뮤니티\nDON'T BE에서 만나요."
p1 : 이건 string으로 추출하면 좋을 것 같습니다!

2024-01-06 16:31 UTC, chanubc commented on feature/src/main/res/layout/activity_login.xml
> +            android:layout_marginLeft="27dp"
p2 : left right 보다는 start end를 쓰는게 좋다고 합니다!

아랍권에서는 언어 자체가 좌 우가 달라서 기기 좌우가 변경 될 수 있데요!

2024-01-06 16:31 UTC, chanubc commented on feature/src/main/res/layout/activity_login.xml
> +            android:layout_marginLeft="26dp"
p2 : 얘두요!

2024-01-06 16:31 UTC, chanubc commented on feature/src/main/res/layout/activity_login.xml
> +            app:layout_constraintStart_toStartOf="parent" />
엇 여기선 잘 되있네요ㅎㅎ

2024-01-06 16:31 UTC, chanubc commented on feature/src/main/java/com/teamdontbe/feature/login/LoginActivity.kt
> +            Log.i(ContentValues.TAG, "카카오계정으로 로그인 성공 ${token.accessToken}")
콜백 함수 폼 미쳤네요..

2024-01-07 09:36 UTC, sohyun127 requested changes
P1 리뷰 수정해주시고 push 해주세요-!! 먼지 카카오 로그인까지... 넌 천재 개발자야

2024-01-07 09:36 UTC, sohyun127 commented on feature/src/main/java/com/teamdontbe/feature/login/LoginActivity.kt
> +                        callback = callback
P1 : 요 부분 보일러 코드이니, 함수화 하여 호출하는 방식으로 바꾸면 재사용 가능할 것 같습니다-!

2024-01-07 09:36 UTC, sohyun127 commented on feature/src/main/java/com/teamdontbe/feature/login/LoginActivity.kt
> +                } else {
P2 : 전체적으로 if문 depth가 깊어서 가독성이 저하되어 보입니다! (어디 블럭에 해당하는 건지 헷갈림.) 
나중에 리팩토링할 때 when문으로 바꿔보면 좋을 것 같아요~!

2024-01-07 09:36 UTC, sohyun127 commented on feature/src/main/java/com/teamdontbe/feature/login/LoginActivity.kt
> +    private fun goMain() {
P1 : 일반적으로 go보단 navigate를 많이 쓰는 것 같아요!! 저희도 navigate으로 통일해서 쓰는 건 어떤가요-?!
그리고, 함수명은 최대한 자세하게! 축약해서 적지 않아 보도록 합시다!! 한달 뒤에 가면 자기가 쓴 코드도 거의 까먹는데, 처음 코드를 보는 사람에게는 코드가 더 더 친절해야겠죠?
```suggestion
    private fun navigateToMainActiviy() {
```

2024-01-07 09:36 UTC, sohyun127 commented on feature/src/main/java/com/teamdontbe/feature/login/LoginActivity.kt
> +    }
P1 : 이 함수는 로그인 로직에는 필요 없으니, 해시키 모두 등록하면 지워주세요-!!

2024-01-08 08:31 UTC, Eonji-sw commented on feature/src/main/java/com/teamdontbe/feature/login/LoginActivity.kt
> +    private fun goMain() {
navigateToMainActivity로 네이밍 변경 했습니다!

2024-01-08 08:33 UTC, Eonji-sw commented on feature/src/main/res/layout/activity_login.xml
> +            android:text="온화한 커뮤니티\nDON'T BE에서 만나요."
이후에 string으로 뺏어욤

2024-01-08 08:34 UTC, Eonji-sw commented on feature/src/main/res/layout/activity_login.xml
> +            android:layout_marginLeft="27dp"
엇 뇌 빼고 그냥 left로 했네요 ㅋㅋㅋ
수정했습니다..! 이런 실수를 하다니
꼼꼼한 코리 감동 ㅎ

2024-01-08 08:35 UTC, Eonji-sw commented on feature/src/main/res/layout/activity_login.xml
> +            android:layout_marginLeft="26dp"
같이 바꿨슴다~

2024-01-08 08:37 UTC, Eonji-sw commented on feature/src/main/java/com/teamdontbe/feature/login/LoginActivity.kt
> +            Log.i(ContentValues.TAG, "카카오계정으로 로그인 성공 ${token.accessToken}")
어우 너무 잘 고쳐주셔서 감동..!
실패 분기 처리 많은 코드도 봤었는데 일단 되는지 먼저 보자는 마인드로 간단하게 구현했었어요 ㅋㅋㅋ

2024-01-08 09:51 UTC, Eonji-sw commented on feature/src/main/java/com/teamdontbe/feature/login/LoginActivity.kt
> +    private fun kakaoLoginBtnClickListener() {
바꿨어요! 완벽해지겠슴다..!

2024-01-08 10:06 UTC, Eonji-sw commented on feature/src/main/java/com/teamdontbe/feature/login/LoginActivity.kt
> +    }
넵 안드 모두 등록한거 확인하면 지울게용

2024-01-08 10:15 UTC, Eonji-sw commented on feature/src/main/java/com/teamdontbe/feature/login/LoginActivity.kt
> +                        callback = callback
setKakaoCallback 이름으로 함수 만들었어요!

2024-01-08 10:26 UTC, Eonji-sw commented on feature/src/main/java/com/teamdontbe/feature/login/LoginActivity.kt
> +                } else {
했는데 맞을까용..?

2024-01-08 10:43 UTC, sohyun127 approved these changes
LGTM 👍 머지해주세요~~

2024-01-08 13:31 UTC, merged