Feature/#48 signup profile
TeamDon-tBe/ANDROID pull request #52
Opened 2024-01-10 20:56 UTC by chanubc

## ✅ 𝗖𝗵𝗲𝗰𝗸-𝗟𝗶𝘀𝘁
- merge할 브랜치의 위치를 확인해 주세요(main❌/develop⭕)
- 리뷰가 필요한 경우 리뷰어를 지정해 주세요
- 리뷰는 (아직 미정)에 진행됩니다.
- P1 단계의 리뷰는 (아직 미정)까지 반영합니다.
- Approve된 PR은 assigner가 머지하고, 수정 요청이 온 경우 수정 후 다시 push를 합니다.

## 📌 𝗜𝘀𝘀𝘂𝗲𝘀
- closed #48 

## 📎𝗪𝗼𝗿𝗸 𝗗𝗲𝘀𝗰𝗿𝗶𝗽𝘁𝗶𝗼𝗻
- 중복확인 로직 구현
- 샐랙터 버튼 구현

## 📷 𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁
https://github.com/TeamDon-tBe/ANDROID/assets/106955456/8bd3d068-dfd2-4b22-94d8-7c199dceadd5

## 💬 𝗧𝗼 𝗥𝗲𝘃𝗶𝗲𝘄𝗲𝗿𝘀
컨플릭 해결은 일어나서 할깨요ㅠ

2024-01-11 05:27 UTC, Eonji-sw reviewed
수고하셨어용! 많이 공부해서 단단해지면 쑥쑥 쿼카햄 나뭇잎 옴뇸뇸

2024-01-11 05:27 UTC, Eonji-sw commented on feature/src/main/java/com/teamdontbe/feature/login/SignUpProfileActivity.kt
> +                binding.tvSignUpAgreeMessage.apply {
P1 : 보일러 코드!! if else 더 안으로 넣거나 삼항 연산자 사용도 가눙하지 않을까요?

2024-01-11 05:27 UTC, Eonji-sw commented on feature/src/main/java/com/teamdontbe/feature/login/SignUpProfileViewModel.kt
> +    private val testNick = "aaa"
P3 : ㅋㅋㅋㅋ testNick 계속 해당 문자열로 사용하나유?

2024-01-11 05:27 UTC, Eonji-sw commented on feature/src/main/res/layout/activity_sign_up_profile.xml
> +            android:background="?attr/selectableItemBackground"
P3 : 오잉 ?attr/ 는 뭔가요??

2024-01-11 05:27 UTC, Eonji-sw commented on feature/src/main/res/layout/activity_sign_up_profile.xml
> +            android:text="@string/btn_onboarding_next"
P3 : 여러 곳에 사용되는 경우 스트링 네이밍을 바꿔도 괜찮지 않을까요?

2024-01-11 05:27 UTC, Eonji-sw commented on feature/src/main/res/values/strings.xml
> +    <string name="sign_up_profile_check_text">*중복된 닉네임인지 확인해주세요</string>
P3 : 이 친구만 마침표가 안붙는게 맞아요?

2024-01-11 07:33 UTC, sohyun127 requested changes
머리 잘 자르셨네요 
화이팅 화이팅  화이팅 화이팅  화이팅 화이팅

2024-01-11 07:33 UTC, sohyun127 commented on feature/src/main/java/com/teamdontbe/feature/login/SignUpProfileActivity.kt
> +        binding.vm = viewModel
p3 : ㅋㅋㅋㅋㅋㅋㅋ잊어버리지 말기

2024-01-11 07:33 UTC, sohyun127 commented on feature/src/main/java/com/teamdontbe/feature/login/SignUpProfileActivity.kt
> +            viewModel.validateNickName(nickName)
P1 : 
```suggestion
            viewModel.validateNickName(binding.etSignUpAgreeText.text.toString())
```
변수 생성 안해도 되어 보입니다-! 오히려 xml id를 et_sign_up_agree_nickname으로 직관적으로 수정하면 좋을듯!

2024-01-11 07:33 UTC, sohyun127 commented on feature/src/main/java/com/teamdontbe/feature/login/SignUpProfileActivity.kt
> +                binding.tvSignUpAgreeMessage.apply {
p3 : 린정

2024-01-11 07:33 UTC, sohyun127 commented on feature/src/main/res/drawable/shape_radius4_rect.xml
P1 : 네이밍 컨벤션!! shape_4_rect 변경 plz
보니깐 다른 것도 네이밍 바꿔야 할듯!! 한번에 바꿔주세유~~

2024-01-11 07:33 UTC, sohyun127 commented on feature/src/main/res/values/strings.xml
> +    <string name="sign_up_profile_edit_hint">닉네임을 입력해주세요</string>
P1 : 여기도 마침표 붙여야 됨!

2024-01-11 07:33 UTC, sohyun127 commented on feature/src/main/res/values/strings.xml
> +    <string name="sign_up_profile_check_text">*중복된 닉네임인지 확인해주세요</string>
P1 : 붙여야 된다고 합니둥! 붙어주세요~

2024-01-11 08:26 UTC, chanubc commented on feature/src/main/java/com/teamdontbe/feature/login/SignUpProfileActivity.kt
> +                binding.tvSignUpAgreeMessage.apply {
[390fd1d](https://github.com/TeamDon-tBe/ANDROID/pull/52/commits/390fd1dbf5f28d1b9316da75c4448e89df683d55)

2024-01-11 08:28 UTC, chanubc commented on feature/src/main/res/values/strings.xml
> +    <string name="sign_up_profile_check_text">*중복된 닉네임인지 확인해주세요</string>
[93bf666](https://github.com/TeamDon-tBe/ANDROID/pull/52/commits/93bf666d021a1608872057160fefe7606c693a78)

2024-01-11 08:33 UTC, chanubc commented on feature/src/main/java/com/teamdontbe/feature/login/SignUpProfileActivity.kt
> +            viewModel.validateNickName(nickName)
[22c39d2](https://github.com/TeamDon-tBe/ANDROID/pull/52/commits/22c39d22fbb084c36e0635d13fe6e424e493464d)

2024-01-11 08:37 UTC, chanubc commented on feature/src/main/java/com/teamdontbe/feature/login/SignUpProfileActivity.kt
> +            viewModel.validateNickName(nickName)
[9794671](https://github.com/TeamDon-tBe/ANDROID/pull/52/commits/97946718707333540078552f5b2f00cf6f69e5fa)

2024-01-12 08:50 UTC, sohyun127 approved these changes
LGTM 👍

2024-01-12 08:52 UTC, merged