[Feature/#75] kakao login 서버 API 연결
TeamDon-tBe/ANDROID pull request #76
Opened 2024-01-13 22:38 UTC by Eonji-sw

## ✅ 𝗖𝗵𝗲𝗰𝗸-𝗟𝗶𝘀𝘁
- merge할 브랜치의 위치를 확인해 주세요(main❌/develop⭕)
- 리뷰가 필요한 경우 리뷰어를 지정해 주세요
- 리뷰는 (아직 미정)에 진행됩니다.
- P1 단계의 리뷰는 (아직 미정)까지 반영합니다.
- Approve된 PR은 assigner가 머지하고, 수정 요청이 온 경우 수정 후 다시 push를 합니다.

## 📌 𝗜𝘀𝘀𝘂𝗲𝘀
- closed #75

## 📎𝗪𝗼𝗿𝗸 𝗗𝗲𝘀𝗰𝗿𝗶𝗽𝘁𝗶𝗼𝗻
- Kakao Login 서버 API 연결

## 📷 𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁
<img width="369" alt="스크린샷 2024-01-14 오전 7 38 03" src="https://github.com/TeamDon-tBe/ANDROID/assets/85453429/277fb44f-ca31-43b7-8aa9-bd5549f76357">

## 💬 𝗧𝗼 𝗥𝗲𝘃𝗶𝗲𝘄𝗲𝗿𝘀
- 화면 이동은 막아놓음

2024-01-14 17:20 UTC, sohyun127 requested changes
첫 카카오 로그인 게시!!! 먼지 최고

2024-01-14 17:20 UTC, sohyun127 commented on feature/src/main/java/com/teamdontbe/feature/login/LoginViewModel.kt
> +            _postLogin.value = UiState.Success(it)
```suggestion
 if (it != null) {
  _postLogin.value = UiState.Success(it)
 }else{
   _postLogin.value = UiState.Empty(it)
 }
           
```
p1 : base response의 data를 nullable로 가져가고자 합니다! 
data가 non-null인 것도 있어서 base response를 두개로 만들려고 했으나, 나중에 dto가 nullable로 변할 수도 있어서(변경 사항에 따라) 미리 null 대응을 해두면 좋을 것 같아요!

따라서 null 일 때도 분기처리 따로 해주면 좋을 것 같아요-!

2024-01-15 05:55 UTC, Eonji-sw commented on data-remote/src/main/java/com/teamdontbe/data_remote/api/AuthApiService.kt
수정했어염

2024-01-15 05:55 UTC, Eonji-sw commented on data-remote/src/main/java/com/teamdontbe/data_remote/datasourceimpl/AuthDataSourceImpl.kt
수정완!

2024-01-15 05:55 UTC, Eonji-sw commented on data/src/main/java/com/teamdontbe/data/datasource/AuthDataSource.kt
수정 완

2024-01-15 05:55 UTC, Eonji-sw commented on data/src/main/java/com/teamdontbe/data/dto/BaseResponse.kt
> +    val code: Boolean,
헿헤헤헤

2024-01-15 05:55 UTC, Eonji-sw commented on data/src/main/java/com/teamdontbe/data/repositoryimpl/AuthRepositoryImpl.kt
수정완

2024-01-15 05:58 UTC, Eonji-sw commented on feature/src/main/java/com/teamdontbe/feature/login/LoginViewModel.kt
> +            _postLogin.value = UiState.Success(it)
수정 완~

2024-01-15 07:31 UTC, merged